name: Test Gitea Setup
run-name: ${{ gitea.actor }} is testing Gitea Actions 🚀

on:
  workflow_dispatch:

jobs:
  hello-world:
    runs-on: gitea
    steps:
      - name: Print Hello World
        run: echo "Hello World"
      
      - name: Show Environment Info
        run: |
          echo "Runner OS: ${{ runner.os }}"
          echo "Repository: ${{ gitea.repository }}"
          echo "Actor: ${{ gitea.actor }}"
          echo "Event: ${{ gitea.event_name }}"
          echo "Ref: ${{ gitea.ref }}"
